### ISSUE TITLE
`grids/` without `__init__.py` crashes

### ISSUE THREAD

**Issue by louismartin** [facebookresearch/dora#26]
https://github.com/facebookresearch/dora/blob/a0a65582ca416d022e0251c711510fc8f99280e7/dora/grid.py#L99

`grids.__file__` is None if there is no `__init__.py`.

**Comment by adefossez** [comment]
making the `__init__.py` seems like the most straightforward fix. Allowing for packages without an `__init__.py` just makes everything more complex for no real gain as far as I can tell.
