### ISSUE TITLE
World size by dora_distrib.world_size() is equal to 1 when I have two GPU's

### ISSUE THREAD

**Issue by temismink** [facebookresearch/dora#47]
## ❓ Questions

I am training my model on two NVIDIA 4090s, whenever the following code is run:

world_size = dora_distrib.world_size()
print(world_size)

world_size is equal to 1 even though torch.cuda.device_count() returns 2.
I tried wrapping my model in DDP and DataParallel but to no avail.

Would appreciate someone shining light on why this is happening.

Thanks

**Comment by adefossez** [comment]
You are running with `dora run -d` ?

**Comment by temismink** [comment]
> You are running with `dora run -d` ?

@adefossez All working now, thank you!
