### ISSUE TITLE
Run a grid experiment for the first time

### ISSUE THREAD

**Issue by alexisthual** [facebookresearch/dora#49]
## ❓ Questions

When debugging an implementation, I don't want to launch a full grid but a single experiment of this grid instead.

Therefore, I list all experiments of my grid with `dora grid mygrid --dry_run`, select an experiment id `mysig` from this grid and launch it with `dora run -f mysig`.
Unfortunately, this raises `FATAL: Could not find an existing run with sig mysig`.
I get the same error with `dora launch -f mysig`.

In order to circumvent this, what I do is I launch all experiments of my grid with `dora grid mygrid` and cancel them right after with `dora grid mygrid --cancel`.

Is there a more direct way to launch an experiment for the first time?

**Comment by adefossez** [comment]
You just need to add --init after --dry_run, otherwise the grid command writes nothing to disk!
