### ISSUE TITLE
Why only the log file of rank > 0 is created?

### ISSUE THREAD

**Issue by mmarczuk** [facebookresearch/dora#51]
## ❓ Questions

I'm trying to debug a problem with nccl, but I can only see the worker_1.log output file.

I have two gpus and I'm trying to see the logs, but I can only see the log of one, is this [check](https://github.com/facebookresearch/dora/blob/72f778ea7457f3d456c1698ee12564bef049eb0f/dora/executor.py#L83) really necessary?

TIA

**Comment by adefossez** [comment]
worker_1.log is actually the log file of the second worker. When running locally (eg with dora run), the output of the first worker is directly shown in the shell. It is not stored in any file.

**Comment by mmarczuk** [comment]
Got it, makes sense, thanks
