### ISSUE TITLE
Can we train with dora on multiple machines without SLURM? 

### ISSUE THREAD

**Issue by asifjalal** [facebookresearch/dora#55]
Is it possible to use dora with horovod or pytorch DDP? If so, is there any documentation/codebase available?

**Comment by adefossez** [comment]
For single node, just use the `-d` flag. For multi node, you can follow the instructions there: https://github.com/facebookresearch/dora/blob/main/README.md#multi-node-training-without-slurm

**Comment by asifjalal** [comment]
Thanks @adefossez , it worked!
