### ISSUE TITLE
Python Debugger and dora

### ISSUE THREAD

**Issue by javanasse** [facebookresearch/dora#64]
## ❓ Questions

Currently using the `dora` CLI to initiate training.

```console
dora run -d solver=<some/solver> dset=<path/to/data> ...
```

What is the syntax for running the same command but using the `dora` python package?

**Comment by adefossez** [comment]
you mean `python -m dora run -d [...]` ?
sadly the debugger is likely to fail in distributed mode, because it would get started on all workers on individual GPUs...
